Use XML configuration file to disable tabs instead of this settings to avoid huge data stored in cookie!

<form name="tabSettings" action="#">
<table class="settings">
<tbody>
<tr>
    <td><br />Disabled tabs:<br /></td>
</tr>
<tr>
    <td id="tabSettingsContainer">%%placeholder%%</td>
</tr>
<tr>
    <td class="buttons">
        <button onclick="return $d.Panel.saveSettings(this);">Apply</button> &nbsp; &nbsp; &nbsp;
        <button onclick="return $d.Panel.resetSettings(this);">Discard</button>
    </td>
</tr>
</tbody>
</table>
</form>
