<div class="about">
Debeetle is the script allowing to debug PHP scripts on hosts having no debug abilities.<br />
It provides
<ul>
    <li>bounding debugging for specified client IPs and/or cookie;</li>
    <li>two level tabbed view;</li>
    <li>skin customization;</li>
    <li>functionality enhancement.</li>
</ul>

Requirements:
<ul>
    <li>Server-side:
        <ul>
            <li>PHP 5;</li>
            <li>JSON lib;</li>
            <li>mb_string lib.</li>
        </ul>
    </li>
    <li>Client-side:
        <ul>
            <li>IE 9.</li>
        </ul>
    </li>
</ul>

Thanx:
<ul>
    <li><a href="http://jquery.com/" target="_blank">jQuery community</a></li>
    <li><a href="http://sourceforge.net/projects/krumo" target="_blank">Krumo PHP dump</a></li>
    <li><a href="http://leafo.net/lessphp/" target="_blank">lessphp</a></li>
</ul>
</div>
