<div class="todo">
<ul>
    <li>Client: [bug] invalid maxHeight for resizable widget;</li>
    <li>Client: minimize and adopt global frame height;</li>
    <li>Client / developer mode: disablibg caching of:
        <ul>
            <li>JavaScript;</li>
            <li>CSS;</li>
            <li>Frame with templates;</li>
        </ul>
    </li>
    <li>Server: fix internal benches;</li>
    <li>Client: replace javascript alerts;</li>
    <li>Client: finish color theme changing;</li>
    <li>Common: check for updates;</li>
    <li>Common: Plugins:
        <ul>
            <li>bench ???;</li>
            <li>error handling;</li>
            <li>pdo_sql;</li>
            <li>fs browser;</li>
            <li>backdoor (php/shell executor);</li>
        </ul>
    </li>
    <li>Common: JSON response debug, common view, pass to get method HTML/JSON;</li>
    <li>Server: absolute bench plan:
        <ul>
            <li>improve Debeetle::getInternalBenches() by arguments;</li>
            <li>return back $secondValue;</li>
            <li>[later] complex benches logging.</li>
        </ul>
    </li>
    <li>Common: [later] localization;</li>
    <li>Client: [wtf] templates merging.</li>
    <li>Client: top/bottom functionality:
        <ul>
            <li>return;</li>
            <li>fix panel max-height when on bottom.</li>
        </ul>
    </li>
</ul>
</div>
